<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Prooph\EventStore\ReadDirection;

final class Forward extends \Prooph\EventStore\ReadDirection
{
    public const VALUE = 'Forward';

    public function toString(): string
    {
        return self::VALUE;
    }

    public function __toString(): string
    {
        return self::VALUE;
    }
}
