<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Prooph\EventStore\Messages\DeletePersistentSubscriptionResult;

final class DoesNotExist extends \Prooph\EventStore\Messages\DeletePersistentSubscriptionResult
{
    public const VALUE = 'DoesNotExist';

    public function toString(): string
    {
        return self::VALUE;
    }

    public function __toString(): string
    {
        return self::VALUE;
    }
}
