<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Prooph\EventStore\Messages;

abstract class OperationResult
{
    public const OPTIONS = [
        OperationResult\Success::VALUE => OperationResult\Success::class,
        OperationResult\PrepareTimeout::VALUE => OperationResult\PrepareTimeout::class,
        OperationResult\CommitTimeout::VALUE => OperationResult\CommitTimeout::class,
        OperationResult\ForwardTimeout::VALUE => OperationResult\ForwardTimeout::class,
        OperationResult\WrongExpectedVersion::VALUE => OperationResult\WrongExpectedVersion::class,
        OperationResult\StreamDeleted::VALUE => OperationResult\StreamDeleted::class,
        OperationResult\InvalidTransaction::VALUE => OperationResult\InvalidTransaction::class,
        OperationResult\AccessDenied::VALUE => OperationResult\AccessDenied::class,
    ];

    final public function __construct()
    {
        $valid = false;

        foreach (self::OPTIONS as $value) {
            if ($this instanceof $value) {
                $valid = true;
                break;
            }
        }

        if (! $valid) {
            $self = get_class($this);
            throw new \LogicException("Invalid OperationResult '$self' given");
        }
    }

    public static function fromString(string $value): self
    {
        if (! isset(self::OPTIONS[$value])) {
            throw new \InvalidArgumentException('Unknown enum value given');
        }

        $class = self::OPTIONS[$value];

        return new $class();
    }

    public function equals(OperationResult $other): bool
    {
        return get_class($this) === get_class($other);
    }

    abstract public function toString(): string;

    abstract public function __toString(): string;
}
