<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStore\Messages;

/**
 * Protobuf enum <code>Prooph\EventStore\Messages\ScavengeDatabaseCompleted\ScavengeResult</code>
 */
class ScavengeDatabaseCompleted_ScavengeResult
{
    /**
     * Generated from protobuf enum <code>Success = 0;</code>
     */
    const Success = 0;
    /**
     * Generated from protobuf enum <code>InProgress = 1;</code>
     */
    const InProgress = 1;
    /**
     * Generated from protobuf enum <code>Failed = 2;</code>
     */
    const Failed = 2;
}
