<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStore\Messages;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Prooph.EventStore.Messages.StreamEventAppeared</code>
 */
class StreamEventAppeared extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Prooph.EventStore.Messages.ResolvedEvent event = 1;</code>
     */
    private $event = null;

    public function __construct()
    {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.Prooph.EventStore.Messages.ResolvedEvent event = 1;</code>
     * @return \Prooph\EventStore\Messages\ResolvedEvent
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * Generated from protobuf field <code>.Prooph.EventStore.Messages.ResolvedEvent event = 1;</code>
     * @param \Prooph\EventStore\Messages\ResolvedEvent $var
     * @return $this
     */
    public function setEvent($var)
    {
        GPBUtil::checkMessage($var, \Prooph\EventStore\Messages\ResolvedEvent::class);
        $this->event = $var;

        return $this;
    }
}
