<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStore\Messages;

/**
 * Protobuf enum <code>Prooph\EventStore\Messages\SubscriptionDropped\SubscriptionDropReason</code>
 */
class SubscriptionDropped_SubscriptionDropReason
{
    /**
     * Generated from protobuf enum <code>Unsubscribed = 0;</code>
     */
    const Unsubscribed = 0;
    /**
     * Generated from protobuf enum <code>AccessDenied = 1;</code>
     */
    const AccessDenied = 1;
    /**
     * Generated from protobuf enum <code>NotFound = 2;</code>
     */
    const NotFound = 2;
    /**
     * Generated from protobuf enum <code>PersistentSubscriptionDeleted = 3;</code>
     */
    const PersistentSubscriptionDeleted = 3;
    /**
     * Generated from protobuf enum <code>SubscriberMaxCountReached = 4;</code>
     */
    const SubscriberMaxCountReached = 4;
}
