<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Prooph\EventStore\PersistentSubscriptionNakEventAction;

final class Skip extends \Prooph\EventStore\PersistentSubscriptionNakEventAction
{
    public const VALUE = 'Skip';

    public function toString(): string
    {
        return self::VALUE;
    }

    public function __toString(): string
    {
        return self::VALUE;
    }
}
