<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Data;

/**
 * Protobuf enum <code>Prooph\EventStoreClient\Data\NotHandled\NotHandledReason</code>
 */
class NotHandled_NotHandledReason
{
    /**
     * Generated from protobuf enum <code>NotReady = 0;</code>
     */
    const NotReady = 0;
    /**
     * Generated from protobuf enum <code>TooBusy = 1;</code>
     */
    const TooBusy = 1;
    /**
     * Generated from protobuf enum <code>NotMaster = 2;</code>
     */
    const NotMaster = 2;
}
