<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Data;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Prooph.EventStoreClient.Data.PersistentSubscriptionAckEvents</code>
 */
class PersistentSubscriptionAckEvents extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string subscription_id = 1;</code>
     */
    private $subscription_id = '';
    /**
     * Generated from protobuf field <code>repeated bytes processed_event_ids = 2;</code>
     */
    private $processed_event_ids;

    public function __construct()
    {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string subscription_id = 1;</code>
     * @return string
     */
    public function getSubscriptionId()
    {
        return $this->subscription_id;
    }

    /**
     * Generated from protobuf field <code>string subscription_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSubscriptionId($var)
    {
        GPBUtil::checkString($var, true);
        $this->subscription_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes processed_event_ids = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProcessedEventIds()
    {
        return $this->processed_event_ids;
    }

    /**
     * Generated from protobuf field <code>repeated bytes processed_event_ids = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProcessedEventIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->processed_event_ids = $arr;

        return $this;
    }
}
