<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Data;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Prooph.EventStoreClient.Data.ReadEventCompleted</code>
 */
class ReadEventCompleted extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Prooph.EventStoreClient.Data.ReadEventCompleted.ReadEventResult result = 1;</code>
     */
    private $result = 0;
    /**
     * Generated from protobuf field <code>.Prooph.EventStoreClient.Data.ResolvedIndexedEvent event = 2;</code>
     */
    private $event = null;
    /**
     * Generated from protobuf field <code>string error = 3;</code>
     */
    private $error = '';

    public function __construct()
    {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.Prooph.EventStoreClient.Data.ReadEventCompleted.ReadEventResult result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.Prooph.EventStoreClient.Data.ReadEventCompleted.ReadEventResult result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Prooph\EventStoreClient\Data\ReadEventCompleted_ReadEventResult::class);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Prooph.EventStoreClient.Data.ResolvedIndexedEvent event = 2;</code>
     * @return \Prooph\EventStoreClient\Data\ResolvedIndexedEvent
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * Generated from protobuf field <code>.Prooph.EventStoreClient.Data.ResolvedIndexedEvent event = 2;</code>
     * @param \Prooph\EventStoreClient\Data\ResolvedIndexedEvent $var
     * @return $this
     */
    public function setEvent($var)
    {
        GPBUtil::checkMessage($var, \Prooph\EventStoreClient\Data\ResolvedIndexedEvent::class);
        $this->event = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error = 3;</code>
     * @return string
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>string error = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, true);
        $this->error = $var;

        return $this;
    }
}
