<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Internal\Messages;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Prooph.EventStoreClient.Internal.Messages.DeletePersistentSubscription</code>
 */
class DeletePersistentSubscription extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string subscription_group_name = 1;</code>
     */
    private $subscription_group_name = '';
    /**
     * Generated from protobuf field <code>string event_stream_id = 2;</code>
     */
    private $event_stream_id = '';

    public function __construct()
    {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string subscription_group_name = 1;</code>
     * @return string
     */
    public function getSubscriptionGroupName()
    {
        return $this->subscription_group_name;
    }

    /**
     * Generated from protobuf field <code>string subscription_group_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSubscriptionGroupName($var)
    {
        GPBUtil::checkString($var, true);
        $this->subscription_group_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string event_stream_id = 2;</code>
     * @return string
     */
    public function getEventStreamId()
    {
        return $this->event_stream_id;
    }

    /**
     * Generated from protobuf field <code>string event_stream_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEventStreamId($var)
    {
        GPBUtil::checkString($var, true);
        $this->event_stream_id = $var;

        return $this;
    }
}
