<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Internal\Messages;

/**
 * Protobuf enum <code>Prooph\EventStoreClient\Internal\Messages\ReadStreamEventsCompleted\ReadStreamResult</code>
 */
class ReadStreamEventsCompleted_ReadStreamResult
{
    /**
     * Generated from protobuf enum <code>Success = 0;</code>
     */
    const Success = 0;
    /**
     * Generated from protobuf enum <code>NoStream = 1;</code>
     */
    const NoStream = 1;
    /**
     * Generated from protobuf enum <code>StreamDeleted = 2;</code>
     */
    const StreamDeleted = 2;
    /**
     * Generated from protobuf enum <code>NotModified = 3;</code>
     */
    const NotModified = 3;
    /**
     * Generated from protobuf enum <code>Error = 4;</code>
     */
    const Error = 4;
    /**
     * Generated from protobuf enum <code>AccessDenied = 5;</code>
     */
    const AccessDenied = 5;
}
