<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Internal\Data;

/**
 * Generated from protobuf message <code>Prooph.EventStoreClient.Internal.Data.ScavengeDatabase</code>
 */
class ScavengeDatabase extends \Google\Protobuf\Internal\Message
{
    public function __construct()
    {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct();
    }
}
