<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Prooph\EventStore\Messages\ReadEventResult;

final class NotFound extends \Prooph\EventStore\Messages\ReadEventResult
{
    public const VALUE = 'NotFound';

    public function toString(): string
    {
        return self::VALUE;
    }

    public function __toString(): string
    {
        return self::VALUE;
    }
}
