<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Prooph\EventStore\Messages\OperationResult;

final class WrongExpectedVersion extends \Prooph\EventStore\Messages\OperationResult
{
    public const VALUE = 'WrongExpectedVersion';

    public function toString(): string
    {
        return self::VALUE;
    }

    public function __toString(): string
    {
        return self::VALUE;
    }
}
