<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Prooph\EventStore\Messages\VNodeState;

final class PreReplica extends \Prooph\EventStore\Messages\VNodeState
{
    public const VALUE = 'PreReplica';

    public function toString(): string
    {
        return self::VALUE;
    }

    public function __toString(): string
    {
        return self::VALUE;
    }
}
