<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Prooph\EventStore;

final class EventReadStatus
{
    public const OPTIONS = [
        'Success' => 0,
        'NotFound' => 1,
        'NoStream' => 2,
        'StreamDeleted' => 3,
    ];

    public const Success = 0;
    public const NotFound = 1;
    public const NoStream = 2;
    public const StreamDeleted = 3;

    private $name;
    private $value;

    private function __construct(string $name)
    {
        $this->name = $name;
        $this->value = self::OPTIONS[$name];
    }

    public static function Success(): self
    {
        return new self('Success');
    }

    public static function NotFound(): self
    {
        return new self('NotFound');
    }

    public static function NoStream(): self
    {
        return new self('NoStream');
    }

    public static function StreamDeleted(): self
    {
        return new self('StreamDeleted');
    }

    public static function byName(string $value): self
    {
        if (! isset(self::OPTIONS[$value])) {
            throw new \InvalidArgumentException('Unknown enum name given');
        }

        return self::{$value}();
    }

    public static function byValue($value): self
    {
        foreach (self::OPTIONS as $name => $v) {
            if ($v === $value) {
                return self::{$name}();
            }
        }

        throw new \InvalidArgumentException('Unknown enum value given');
    }

    public function equals(EventReadStatus $other): bool
    {
        return get_class($this) === get_class($other) && $this->value === $other->value;
    }

    public function name(): string
    {
        return $this->name;
    }

    public function value()
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return $this->name;
    }
}
