<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Prooph\EventStore;

abstract class PersistentSubscriptionNakEventAction
{
    public const OPTIONS = [
        PersistentSubscriptionNakEventAction\Unknown::VALUE => PersistentSubscriptionNakEventAction\Unknown::class,
        PersistentSubscriptionNakEventAction\Park::VALUE => PersistentSubscriptionNakEventAction\Park::class,
        PersistentSubscriptionNakEventAction\Retry::VALUE => PersistentSubscriptionNakEventAction\Retry::class,
        PersistentSubscriptionNakEventAction\Skip::VALUE => PersistentSubscriptionNakEventAction\Skip::class,
        PersistentSubscriptionNakEventAction\Stop::VALUE => PersistentSubscriptionNakEventAction\Stop::class,
    ];

    final public function __construct()
    {
        $valid = false;

        foreach (self::OPTIONS as $value) {
            if ($this instanceof $value) {
                $valid = true;
                break;
            }
        }

        if (! $valid) {
            $self = get_class($this);
            throw new \LogicException("Invalid PersistentSubscriptionNakEventAction '$self' given");
        }
    }

    public static function fromString(string $value): self
    {
        if (! isset(self::OPTIONS[$value])) {
            throw new \InvalidArgumentException('Unknown enum value given');
        }

        $class = self::OPTIONS[$value];

        return new $class();
    }

    public function equals(PersistentSubscriptionNakEventAction $other): bool
    {
        return get_class($this) === get_class($other);
    }

    abstract public function toString(): string;

    abstract public function __toString(): string;
}
