<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Prooph\EventStore;

final class StreamPosition
{
    public const Start = 0;
    public const End = -1;
}
