<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Prooph\EventStore\Messages\CreatePersistentSubscriptionResult;

final class Fail extends \Prooph\EventStore\Messages\CreatePersistentSubscriptionResult
{
    public const VALUE = 'Fail';

    public function toString(): string
    {
        return self::VALUE;
    }

    public function __toString(): string
    {
        return self::VALUE;
    }
}
