<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Prooph\EventStore\Messages\NotHandledReason;

final class NotReady extends \Prooph\EventStore\Messages\NotHandledReason
{
    public const VALUE = 'NotReady';

    public function toString(): string
    {
        return self::VALUE;
    }

    public function __toString(): string
    {
        return self::VALUE;
    }
}
