<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStore\Internal\Messages;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Prooph.EventStore.Internal.Messages.ConnectToPersistentSubscription</code>
 */
class ConnectToPersistentSubscription extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string subscription_id = 1;</code>
     */
    private $subscription_id = '';
    /**
     * Generated from protobuf field <code>string event_stream_id = 2;</code>
     */
    private $event_stream_id = '';
    /**
     * Generated from protobuf field <code>int32 allowed_in_flight_messages = 3;</code>
     */
    private $allowed_in_flight_messages = 0;

    public function __construct()
    {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string subscription_id = 1;</code>
     * @return string
     */
    public function getSubscriptionId()
    {
        return $this->subscription_id;
    }

    /**
     * Generated from protobuf field <code>string subscription_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSubscriptionId($var)
    {
        GPBUtil::checkString($var, true);
        $this->subscription_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string event_stream_id = 2;</code>
     * @return string
     */
    public function getEventStreamId()
    {
        return $this->event_stream_id;
    }

    /**
     * Generated from protobuf field <code>string event_stream_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEventStreamId($var)
    {
        GPBUtil::checkString($var, true);
        $this->event_stream_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 allowed_in_flight_messages = 3;</code>
     * @return int
     */
    public function getAllowedInFlightMessages()
    {
        return $this->allowed_in_flight_messages;
    }

    /**
     * Generated from protobuf field <code>int32 allowed_in_flight_messages = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setAllowedInFlightMessages($var)
    {
        GPBUtil::checkInt32($var);
        $this->allowed_in_flight_messages = $var;

        return $this;
    }
}
