<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStore\Internal\Messages;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Prooph.EventStore.Internal.Messages.ResolvedIndexedEvent</code>
 */
class ResolvedIndexedEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Prooph.EventStore.Internal.Messages.EventRecord event = 1;</code>
     */
    private $event = null;
    /**
     * Generated from protobuf field <code>.Prooph.EventStore.Internal.Messages.EventRecord link = 2;</code>
     */
    private $link = null;

    public function __construct()
    {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.Prooph.EventStore.Internal.Messages.EventRecord event = 1;</code>
     * @return \Prooph\EventStore\Internal\Messages\EventRecord
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * Generated from protobuf field <code>.Prooph.EventStore.Internal.Messages.EventRecord event = 1;</code>
     * @param \Prooph\EventStore\Internal\Messages\EventRecord $var
     * @return $this
     */
    public function setEvent($var)
    {
        GPBUtil::checkMessage($var, \Prooph\EventStore\Internal\Messages\EventRecord::class);
        $this->event = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Prooph.EventStore.Internal.Messages.EventRecord link = 2;</code>
     * @return \Prooph\EventStore\Internal\Messages\EventRecord
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * Generated from protobuf field <code>.Prooph.EventStore.Internal.Messages.EventRecord link = 2;</code>
     * @param \Prooph\EventStore\Internal\Messages\EventRecord $var
     * @return $this
     */
    public function setLink($var)
    {
        GPBUtil::checkMessage($var, \Prooph\EventStore\Internal\Messages\EventRecord::class);
        $this->link = $var;

        return $this;
    }
}
